'Thats The Way' exercise finished
ScaleUp-Academy-ExcellenTeam22/yam-mesika-weeks-5-6-michall1900 pull request #1
Opened 2022-03-14 06:59 UTC by michall1900

Hey itayday,
Please check the exercise,
Thanks in advance .

2022-03-14 17:22 UTC, talbarfm commented
You have conflicts ! make sure to fix them!

2022-03-14 17:23 UTC, talbarfm commented
Pay attention to add a capital letter to the commit message

2022-03-14 17:36 UTC, talbarfm requested changes

2022-03-14 17:36 UTC, talbarfm commented on 5.1 Ex/5.1 Thats The Way.py
> +import os
Add a newline the imports and the consts

2022-03-14 17:36 UTC, talbarfm commented on 5.1 Ex/5.1 Thats The Way.py
> +def find_files_at_path_with_wanted_prefix(path='.', prefix=FILES_PREFIX):
thats a way too long function name - find_files_with_prefix should suffice

2022-03-14 17:36 UTC, talbarfm commented on 5.1 Ex/5.1 Thats The Way.py
> +    files_list_with_wanted_suffix = [file for file in os.listdir(path) if file.startswith(prefix)]
just return the new list - you dont  have to assign it to a variable

2022-03-14 17:36 UTC, talbarfm commented on 5.1 Ex/5.1 Thats The Way.py
> +def find_files_at_path_with_wanted_prefix(path='.', prefix=FILES_PREFIX):
I would use partial for this use, or wrap the function with another function that is suited for this exercise requests - youve made a generic function but the default values are not generic therefore should not be there

2022-03-14 17:36 UTC, talbarfm commented on 5.1 Ex/5.1 Thats The Way.py
> +wanted_path = input("Please Enter wanted path: ")
wrap all of this inside a function - you can name it main, you can name it what ever you want, make sure its not executed when this file is imported

2022-03-14 17:36 UTC, talbarfm commented on 5.1 Ex/5.1 Thats The Way.py
> +print("The list is:")
use list comprehension instead of this for loop

2022-03-14 17:36 UTC, talbarfm commented on 5.1 Ex/5.1 Thats The Way.py
> +def find_files_at_path_with_wanted_prefix(path='.', prefix=FILES_PREFIX):
Add type hints instead of documenting the file type in a comment

2022-03-14 17:36 UTC, talbarfm commented on 5.1 Ex/5.1 Thats The Way.py
> +def find_files_at_path_with_wanted_prefix(path='.', prefix=FILES_PREFIX):
Add return type to the funciton. the -> syntax

2022-03-14 17:36 UTC, talbarfm commented on 5.1 Ex/5.1 Thats The Way.py
> +    The function receives path to search in and prefix to search files with that prefix.
You can join these two sentences to one and remove the second "The funciton"

2022-03-14 17:36 UTC, talbarfm commented on 5.1 Ex/5.1 Thats The Way.py
> +FILES_PREFIX = "deep"
Why is this a const if you use it once?

2022-03-14 17:51 UTC, michall1900 commented on 5.1 Ex/5.1 Thats The Way.py
> +wanted_path = input("Please Enter wanted path: ")
Tal

2022-03-14 19:54 UTC, talbarfm commented
@itayday

2022-03-26 12:16 UTC, talbarfm requested changes
Good job!

2022-03-26 12:16 UTC, talbarfm commented on 5.1 Ex/5.1 Thats The Way.py
> +"""Searching at given path files with given prefix, create a list of files name's
Add a newline after """

2022-03-26 12:16 UTC, talbarfm commented on main.py
> +
????? what is this file doint here?

2022-03-26 12:16 UTC, talbarfm commented on 5.1 Ex/5.1 Thats The Way.py
> +    [print(file_name) for file_name in files_list]
oh no no no 
https://stackoverflow.com/questions/5753597/is-it-pythonic-to-use-list-comprehensions-for-just-side-effects

2022-03-26 12:16 UTC, talbarfm commented on 5.1 Ex/5.1 Thats The Way.py
> +    @param prefix: For search files with that prefix
. in the end

2022-03-26 12:16 UTC, talbarfm commented on 5.1 Ex/5.1 Thats The Way.py
> +"""Searching at given path files with given prefix, create a list of files name's
You dont have to add this description,  the function description is enough

2022-03-26 12:16 UTC, talbarfm commented on 5.1 Ex/5.1 Thats The Way.py
> +def send_specific_data() -> list:
I would replace this function with a partial that sets the prefix to deep, anyway, good thinking! the coupling to the specific path is redundant in my opinion

2022-03-30 07:42 UTC, lovodkin93 approved these changes
Great job and great documentation!

2022-03-30 07:44 UTC, merged