I don't have vinaigrette ex - finished
ScaleUp-Academy-ExcellenTeam22/yam-mesika-weeks-5-6-michall1900 pull request #2
Opened 2022-03-14 12:30 UTC by michall1900

Hey itayday,
Just finished that ex, please check it.
Thanks in advance

2022-03-26 11:57 UTC, talbarfm requested changes
Good job!!!

2022-03-26 11:57 UTC, talbarfm commented on 5.1 Ex/I don't have vinaigrette.py
> +"""Receives from user two different dates in format YYYY-MM-DD,
You can remove the description

2022-03-26 11:57 UTC, talbarfm commented on 5.1 Ex/I don't have vinaigrette.py
> +    if first_date.date() == second_date.date():
Why do you need this condition? the amount of time it saves isnt worth the two lines of code there are in there

2022-03-26 11:57 UTC, talbarfm commented on 5.1 Ex/I don't have vinaigrette.py
> +    return (min(first_date, second_date) + timedelta(seconds=random_dif_sec)).strftime(date_format)
I wouldnt return it as an str, I would return it as a date, that way it will be more generic

2022-03-26 11:57 UTC, talbarfm commented on 5.1 Ex/I don't have vinaigrette.py
> +def rand_time(first_date: datetime, second_date: datetime, date_format: str) -> str:
I wouldnt add the date_format in there, but If you did I would give it a default value

2022-03-26 11:57 UTC, talbarfm commented on 5.1 Ex/I don't have vinaigrette.py
> +def main_i_dont_have_v():
i dont have v? what is v? give full names

2022-03-26 11:57 UTC, talbarfm commented on 5.1 Ex/I don't have vinaigrette.py
> +def rand_time(first_date: datetime, second_date: datetime, date_format: str) -> str:
I think you can come up with better names then first_date and second_date - dont they have anymore meaning?

2022-03-26 11:57 UTC, talbarfm commented on 5.1 Ex/I don't have vinaigrette.py
> +    :param first_date: first time type for tip of range.
tip of range of what? is it a time? is it a date? this description is a bit confusing

2022-03-26 11:57 UTC, talbarfm commented on 5.1 Ex/I don't have vinaigrette.py
> +def is_date_in_week_day(date: str, day: int) -> bool:
nice creating of a generic function!

2022-03-26 11:57 UTC, talbarfm commented on 5.1 Ex/I don't have vinaigrette.py
> +    first_date_str = input("Please enter your first date in format YYYY-MM-DD: ")
dont add tests and input from user, if you do split to different functions

2022-03-26 11:57 UTC, talbarfm commented on 5.1 Ex/I don't have vinaigrette.py
> +    if is_date_in_week_day(date_picked, 0):
you can reduce this if else to a singel line of code by using oneline if for creating the string output, and then just print it

2022-03-26 11:57 UTC, talbarfm commented on 5.1 Ex/I don't have vinaigrette.py
> +    # Check if it is monday and print result.
You good function names make this comment redundant :)

2022-03-26 11:57 UTC, talbarfm commented on 5.1 Ex/I don't have vinaigrette.py
> +def rand_time(first_date: datetime, second_date: datetime, date_format: str) -> str:
Is it a time? is it a date? no abbreviations, so random_time, I would pick a better name

2022-03-27 18:12 UTC, michall1900 commented on 5.1 Ex/I don't have vinaigrette.py
> +def is_date_in_week_day(date: str, day: int) -> bool:
Thanks :)

2022-03-30 07:26 UTC, lovodkin93 approved these changes

2022-03-30 07:39 UTC, merged