Finished piece of cake ex
ScaleUp-Academy-ExcellenTeam22/yam-mesika-weeks-5-6-michall1900 pull request #4
Opened 2022-03-14 20:44 UTC by michall1900

Hey itayday and talbarfm,
Please check the exercise,
Thanks in advance .

2022-03-26 10:42 UTC, talbarfm requested changes
Good job!!!@

2022-03-26 10:42 UTC, talbarfm commented on 5.2/Piece of cake.py
> +    """Receives dictionary when key its ingredients name's and item is their price for 100 g,
newline after """

2022-03-26 10:42 UTC, talbarfm commented on 5.2/Piece of cake.py
> +def get_recipe_price(prices: dict, optionals: list = None, **gram_ingredients: dict) -> float or None:
float or None is incorrect, read about typing.Union

2022-03-26 10:42 UTC, talbarfm commented on 5.2/Piece of cake.py
> +    if not prices.keys() == gram_ingredients.keys():
Cant you supply a price that will not be used in this function? seems like you are too harsh in your limitations, without a reason

2022-03-26 10:42 UTC, talbarfm commented on 5.2/Piece of cake.py
> +        print("There are missing key/s at one of the dicts")
I would raise an exception and not print anything - afterwards I can catch it and do anything I want with it

2022-03-26 10:42 UTC, talbarfm commented on 5.2/Piece of cake.py
> +    final_price = 0
Read about functools.reduce and replace this for loop with it

2022-03-26 10:42 UTC, talbarfm commented on 5.2/Piece of cake.py
> +    # Just doing and printing some tests.
You dont have to document this, its obvious

2022-03-26 10:42 UTC, talbarfm commented on 5.2/Piece of cake.py
> +    print(get_recipe_price({'chocolate': 18, 'milk': 8}, chocolate=200, milk=100))
maybe a lambda to reduce the repeats on these two lines? just for the fun of it?

2022-03-30 07:05 UTC, lovodkin93 approved these changes
very good!

2022-03-30 07:41 UTC, merged